# MP2BTP Configurations
VERBOSE_MODE = true
NUM_MULTIPATH = 1
MY_IP_ADDRS = ["117.16.244.33"]
LISTEN_PORT         = 4000
BIND_PORT           = 5000
EQUIC_ENABLE        = true
EQUIC_PATH          = "./fectun"
EQUIC_APP_SRC_PORT  = 6000
EQUIC_APP_DST_PORT  = 5000
EQUIC_TUN_SRC_PORT  = 7000
EQUIC_TUN_DST_PORT  = 7000
EQUIC_FEC_MODE      = false
SEGMENT_SIZE        = 2097152
FEC_SEGMENT_SIZE    = 2466816
THROUGHPUT_PERIOD   = 0.1
THROUGHPUT_WEIGHT   = 0.1
MULTIPATH_THRESHOLD_THROUGHPUT = 100.0
MULTIPATH_THRESHOLD_SEND_COMPLETE_TIME = 0.0000000001
CLOSE_TIMEOUT_PERIOD = 200

[[peer_addr]]  # Offset=0
Addr = "117.16.244.33"
NumChild = 1
ChildOffset = 1

[[peer_addr]]  # Offset=1
Addr = "117.16.244.33"
NumChild = 0
ChildOffset = 0
